using System;
using System.Collections.Generic;

#nullable disable

namespace WebApi.Entities
{
    public partial class Ipclogtran
    {
        public DateTime ipctransdate { get; set; }
        public DateTime ipcworkdate { get; set; }
        public long ipctransid { get; set; }
        public string ipctrancode { get; set; }
        public string tranref { get; set; }
        public string senderbank { get; set; }
        public string receiverbank { get; set; }
        public string senderchannel { get; set; }
        public string receiverchannel { get; set; }
        public string ccyid { get; set; }
        public string sourceid { get; set; }
        public string destid { get; set; }
        public string sourcetranref { get; set; }
        public string userid { get; set; }
        public string usercurapp { get; set; }
        public string nextuserapp { get; set; }
        public string listuserapp { get; set; }
        public string trandesc { get; set; }
        public string status { get; set; }
        public string statushis { get; set; }
        public string listuserprs { get; set; }
        public int apprsts { get; set; }
        public string offlsts { get; set; }
        public bool deleted { get; set; }
        public string desttranref { get; set; }
        public string desterrorcode { get; set; }
        public string errorcode { get; set; }
        public string errordesc { get; set; }
        public bool? online { get; set; }
        public string char01 { get; set; }
        public string char02 { get; set; }
        public string char03 { get; set; }
        public string char04 { get; set; }
        public string char05 { get; set; }
        public string char06 { get; set; }
        public string char07 { get; set; }
        public string char08 { get; set; }
        public string char09 { get; set; }
        public string char10 { get; set; }
        public string char11 { get; set; }
        public string char12 { get; set; }
        public string char13 { get; set; }
        public string char14 { get; set; }
        public string char15 { get; set; }
        public string char16 { get; set; }
        public string char17 { get; set; }
        public string char18 { get; set; }
        public string char19 { get; set; }
        public string char20 { get; set; }
        public string char21 { get; set; }
        public string char22 { get; set; }
        public string char23 { get; set; }
        public string char24 { get; set; }
        public string char25 { get; set; }
        public string char26 { get; set; }
        public string char27 { get; set; }
        public string char28 { get; set; }
        public string char29 { get; set; }
        public string char30 { get; set; }
        public string char31 { get; set; }
        public string char32 { get; set; }
        public string char33 { get; set; }
        public string char34 { get; set; }
        public string char35 { get; set; }
        public string char36 { get; set; }
        public string char37 { get; set; }
        public string char38 { get; set; }
        public string char39 { get; set; }
        public string char40 { get; set; }
        public string char41 { get; set; }
        public string char42 { get; set; }
        public string char43 { get; set; }
        public string char44 { get; set; }
        public string char45 { get; set; }
        public string char46 { get; set; }
        public string char47 { get; set; }
        public string char48 { get; set; }
        public string char49 { get; set; }
        public string char50 { get; set; }
        public string char51 { get; set; }
        public string char52 { get; set; }
        public string char53 { get; set; }
        public string char54 { get; set; }
        public string char55 { get; set; }
        public string char56 { get; set; }
        public string char57 { get; set; }
        public string char58 { get; set; }
        public string char59 { get; set; }
        public string char60 { get; set; }
        public string char61 { get; set; }
        public string char62 { get; set; }
        public string char63 { get; set; }
        public string char64 { get; set; }
        public string char65 { get; set; }
        public string char66 { get; set; }
        public string char67 { get; set; }
        public string char68 { get; set; }
        public string char69 { get; set; }
        public string char70 { get; set; }
        public decimal? num01 { get; set; }
        public decimal? num02 { get; set; }
        public decimal? num03 { get; set; }
        public decimal? num04 { get; set; }
        public decimal? num05 { get; set; }
        public decimal? num06 { get; set; }
        public decimal? num07 { get; set; }
        public decimal? num08 { get; set; }
        public decimal? num09 { get; set; }
        public decimal? num10 { get; set; }
        public decimal? num11 { get; set; }
        public decimal? num12 { get; set; }
        public decimal? num13 { get; set; }
        public decimal? num14 { get; set; }
        public decimal? num15 { get; set; }
        public decimal? num16 { get; set; }
        public decimal? num17 { get; set; }
        public decimal? num18 { get; set; }
        public decimal? num19 { get; set; }
        public decimal? num20 { get; set; }
        public decimal? num21 { get; set; }
        public decimal? num22 { get; set; }
        public decimal? num23 { get; set; }
        public decimal? num24 { get; set; }
        public decimal? num25 { get; set; }
        public decimal? num26 { get; set; }
        public decimal? num27 { get; set; }
        public decimal? num28 { get; set; }
        public decimal? num29 { get; set; }
        public decimal? num30 { get; set; }
        public decimal? num31 { get; set; }
        public decimal? num32 { get; set; }
        public decimal? num33 { get; set; }
        public decimal? num34 { get; set; }
        public decimal? num35 { get; set; }
        public decimal? num36 { get; set; }
        public decimal? num37 { get; set; }
        public decimal? num38 { get; set; }
        public decimal? num39 { get; set; }
        public decimal? num40 { get; set; }
        public decimal? num41 { get; set; }
        public decimal? num42 { get; set; }
        public decimal? num43 { get; set; }
        public decimal? num44 { get; set; }
        public decimal? num45 { get; set; }
        public decimal? num46 { get; set; }
        public decimal? num47 { get; set; }
        public decimal? num48 { get; set; }
        public decimal? num49 { get; set; }
        public decimal? num50 { get; set; }
        public decimal? num51 { get; set; }
        public decimal? num52 { get; set; }
        public decimal? num53 { get; set; }
        public decimal? num54 { get; set; }
        public decimal? num55 { get; set; }
        public decimal? num56 { get; set; }
        public decimal? num57 { get; set; }
        public decimal? num58 { get; set; }
        public decimal? num59 { get; set; }
        public decimal? num60 { get; set; }
        public decimal? num61 { get; set; }
        public decimal? num62 { get; set; }
        public decimal? num63 { get; set; }
        public decimal? num64 { get; set; }
        public decimal? num65 { get; set; }
        public decimal? num66 { get; set; }
        public decimal? num67 { get; set; }
        public decimal? num68 { get; set; }
        public decimal? num69 { get; set; }
        public decimal? num70 { get; set; }
        public string isbatch { get; set; }
        public string batchref { get; set; }
    }
}
